### ISSUE TITLE
click._bashcomplete

### ISSUE THREAD

**Issue by liutiming** [bcbernardo/aw-watcher-ask#1]
Thanks for this awesome watcher!

I have got issues running the watcher with the following traceback and potentially related issues https://github.com/celery/celery/issues/6511  https://github.com/click-contrib/click-repl/issues/72:

I wonder what we can do about this?

```
aw-watcher-ask run --help
Traceback (most recent call last):
  File "/home/timing/.local/bin/aw-watcher-ask", line 5, in <module>
    from aw_watcher_ask.cli import app
  File "/home/timing/.local/lib/python3.8/site-packages/aw_watcher_ask/cli.py", line 12, in <module>
    import typer
  File "/home/timing/.local/lib/python3.8/site-packages/typer/__init__.py", line 29, in <module>
    from .main import Typer as Typer
  File "/home/timing/.local/lib/python3.8/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/home/timing/.local/lib/python3.8/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

**Comment by bcbernardo** [comment]
I've just updated the watcher's dependencies so that it uses Typer>=0.4. This should solve the problem (see https://github.com/tiangolo/typer/issues/278 ).

Can you upgrade or reinstall the package and confirm whether the problem remains?

**Comment by bcbernardo** [comment]
Closing this issue as it appears to be solved. Feel free do add further comments or open a new issue if that is not the case.

**Comment by liutiming** [comment]
Yes it is resolved. Thank you!
