### ISSUE TITLE
Windows support (use go port zenity in python)

### ISSUE THREAD

**Issue by liutiming** [bcbernardo/aw-watcher-ask#3]
`zenity` in python using a UNIX version of `zenity` instead of the `zenity` go port. I am wondering if you have any suggestions how to use go zenity in python?

```python
> python
Python 3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import zenity
>>> zenity.show()
'sudo' is not recognized as an internal or external command,
operable program or batch file.
False
```

Also copy @ncruces for any possible advice :) 

## Steps to set up
In powershell: 
```
choco install -y golang
go get github.com/ncruces/zenity
python -m pip install git+https://github.com/bcbernardo/aw-watcher-ask.git
aw-watcher-ask run --question-id "happiness.level" --question-type="question" --title="My happiness level" --text="Are you feeling happy right now?" --timeout=120 --schedule "29 */1 * * * 30"
```

## Traceback 
<details>
<summary>Details</summary>
aw-watcher-ask run --question-id "happiness.level" --question-type="question" --title="My happiness level" --text="Are you feeling happy right now?" --timeout=120 --schedule "29 */1 * * * 30"
2021-12-19 10:29:05.364 | INFO     | aw_watcher_ask.core:main:132 - Starting new watcher...
2021-12-19T10:29:05.364228+0000 <happiness.level>: INFO - Starting new watcher...
2021-12-19 10:29:05.383 | INFO     | aw_watcher_ask.core:main:149 - Client created and connected to server at http://127.0.0.1:5600.
2021-12-19T10:29:05.383193+0000 <happiness.level>: INFO - Client created and connected to server at http://127.0.0.1:5600.
2021-12-19 10:29:05.400 | INFO     | aw_watcher_ask.core:main:161 - Next execution scheduled to 2021-12-19T10:29:30+00:00.
2021-12-19T10:29:05.400224+0000 <happiness.level>: INFO - Next execution scheduled to 2021-12-19T10:29:30+00:00.
2021-12-19 10:29:29.411 | INFO     | aw_watcher_ask.core:main:167 - New prompt fired. Waiting for user input...
2021-12-19T10:29:29.411130+0000 <happiness.level>: INFO - New prompt fired. Waiting for user input...
'sudo' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\Scripts\aw-watcher-ask.exe\__main__.py", line 7, in <module>
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\aw_watcher_ask\cli.py", line 135, in run
    main(**params)
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\aw_watcher_ask\core.py", line 180, in main
    answer = _ask_one(
  File "C:\Users\timing\anaconda3\envs\aw-watcher\lib\site-packages\aw_watcher_ask\core.py", line 50, in _ask_one
    success, content = zenity.show(
TypeError: cannot unpack non-iterable bool object

</details>

**Comment by ncruces** [comment]
I guess to have it work you'd have to put my go port in the `PATH` ahead of the any other `zenity`. I don't have any Windows installers that do this for you.

But Python also can't be calling other Unix stuff like `sudo`.

More importantly, **I have to wonder why this'd be calling `sudo`**. Unless there's a real easy to explain need, this sounds ***very*** fishy.

**Comment by liutiming** [comment]
Good point and thanks a lot for the kind help @ncruces!

I checked the environment and `zenity` imported here is probably 
```
pyzenity                  2.0.0                    pypi_0    pypi
```
I tried on my Mac as well and `sudo` is required on both OS with 
```
> python
>>> import zenity
>>> zenity.show()
```

@bcbernardo, maybe it would be a good idea to change the python library that calls `zenity`? Thanks a lot :)

**Comment by liutiming** [comment]
I just realise the `sudo` command may be made to install `zenity` when the library detects that it is missing. Will try to install zenity with brew on my Mac and add go port zenity to my Windows path first and run again. Thanks!

**Comment by ncruces** [comment]
Yes, adding to `PATH` should fix it.

Still not enthusiastic about a library trying to install dependencies at run-time using `sudo`, without even explaining what it's doing.

**Comment by liutiming** [comment]
Thanks! Yup that solved the issue :))
